In [3]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:YOUR_PASSWORD@localhost:5432/skincare_db')

df = pd.read_sql('SELECT * FROM antispot_reviews', engine)
print(df.shape)
df.head(3)

(653867, 21)

,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,...,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd,ingredients,secondary_category,tertiary_category
0,7426392344,5,1.0,None,0,0,0,2020-05-31,I recieved a free sample of Dr. Dennis Gross S...,Great Product,...,hazel,combination,brown,P269122,Alpha Beta Extra Strength Daily Peel Pads,Dr. Dennis Gross Skincare,92.0,"['Step 1:', 'Water/Aqua/Eau, Alcohol Denat. (S...",Treatments,Facial Peels
1,1989003620,2,None,0.1428570002317428,7,6,1,2013-02-28,I was so excited about trying this oil out and...,Not for acne prone skin,...,None,None,None,P218700,100 percent Pure Argan Oil,Josie Maran,49.0,['Argania Spinosa (Argan) Kernel Oil.'],Moisturizers,Face Oils
2,1437452845,4,None,None,0,0,0,2013-02-28,I am in love with this stuff! I am using it as...,Love it!,...,None,None,None,P218700,100 percent Pure Argan Oil,Josie Maran,49.0,['Argania Spinosa (Argan) Kernel Oil.'],Moisturizers,Face Oils

In [43]:
import re

# Signal 1: Ingredient-driven
ingredient_keywords = [
    'niacinamide', 'vitamin c', 'ascorbic acid', 'tranexamic',
    'arbutin', 'kojic', 'azelaic', 'hydroquinone', 'retinol',
    'ferulic', 'glycolic', 'lactic acid', 'aha', 'bha', 'salicylic'
]

# Signal 2: Authority-driven
authority_keywords = [
    # Professional
    'dermatologist', 'derm', 'esthetician', 'skin doctor',
    'board certified', 'recommended by',
    # Social media platforms
    'tiktok', 'reddit', 'youtube', 'instagram', 'pinterest', 'facebook',
    # Influencer language
    'influencer', 'content creator',
    # Ad/sponsored language
    'sponsored', 'gifted', 'paid partnership', 'advertisement'
]

# Signal 3: Price-driven
price_keywords = [
    'affordable', 'dupe', 'cheaper', 'drugstore',
    'splurge', 'worth the price', 'budget', 'pricey',
    'value', 'expensive but', 'save money', 'for the price'
]

# Signal 4: Result-driven
result_keywords = [
    'saw results', 'noticed difference', 'before and after',
    'spots faded', 'skin cleared', 'actually works',
    'real difference', 'visible', 'transformed', 'improved'
]

# Signal 5: Brand-driven
brand_phrases = [
    r'love this brand', r'trust this brand', r'loyal to',
    r'always buy', r'my favorite brand', r'never disappoints',
    r'go.?to brand'
]

In [45]:
def extract_signals(text):
    if not isinstance(text, str):
        return {'ingredient': 0, 'authority': 0, 'price': 0, 'result': 0, 'brand': 0}
    
    t = text.lower()
    return {
        'ingredient': int(any(kw in t for kw in ingredient_keywords)),
        'authority':  int(any(kw in t for kw in authority_keywords)),
        'price':      int(any(kw in t for kw in price_keywords)),
        'result':     int(any(kw in t for kw in result_keywords)),
        'brand':      int(any(re.search(p, t) for p in brand_phrases))
    }

In [47]:
extract_signals("I bought this because my dermatologist recommended niacinamide")

{'ingredient': 1, 'authority': 1, 'price': 0, 'result': 0, 'brand': 0}

In [49]:
# 先刪掉舊的 signal 欄位
signal_cols = ['ingredient', 'authority', 'price', 'result', 'brand']
df = df.drop(columns=[c for c in signal_cols if c in df.columns])

# 再重新 concat
signals = df['review_text'].apply(extract_signals).apply(pd.Series)
df = pd.concat([df, signals], axis=1)
print(df[['ingredient', 'authority', 'price', 'result', 'brand']].sum())

ingredient    48126
authority     34600
price         39211
result        23001
brand          2205
dtype: int64

In [51]:
from sqlalchemy import text

# 先刪舊表（如果有的話）
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS antispot_reviews_signals"))
    conn.commit()

df.to_sql('antispot_reviews_signals', engine, index=False, if_exists='replace')
print("Done")

Done

In [19]:
df.head()

,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,...,brand_name,price_usd,ingredients,secondary_category,tertiary_category,ingredient,authority,price,result,brand
0,7426392344,5,1.0,None,0,0,0,2020-05-31,I recieved a free sample of Dr. Dennis Gross S...,Great Product,...,Dr. Dennis Gross Skincare,92.0,"['Step 1:', 'Water/Aqua/Eau, Alcohol Denat. (S...",Treatments,Facial Peels,0,0,0,0,0
1,1989003620,2,None,0.1428570002317428,7,6,1,2013-02-28,I was so excited about trying this oil out and...,Not for acne prone skin,...,Josie Maran,49.0,['Argania Spinosa (Argan) Kernel Oil.'],Moisturizers,Face Oils,0,0,0,0,0
2,1437452845,4,None,None,0,0,0,2013-02-28,I am in love with this stuff! I am using it as...,Love it!,...,Josie Maran,49.0,['Argania Spinosa (Argan) Kernel Oil.'],Moisturizers,Face Oils,0,0,0,0,0
3,1387937957,5,None,0.0,1,1,0,2013-02-27,Resurrect is exactly what this product did to ...,resurrection,...,Josie Maran,49.0,['Argania Spinosa (Argan) Kernel Oil.'],Moisturizers,Face Oils,0,0,1,0,0
4,1290984641,5,None,None,0,0,0,2013-02-27,I got this product as a promo sample and would...,Great promo sample,...,Josie Maran,49.0,['Argania Spinosa (Argan) Kernel Oil.'],Moisturizers,Face Oils,0,0,0,0,0

In [25]:
from pathlib import Path
Path("C:/Users/super/Projects/skincare-sentiment-analysis/data/output").mkdir(exist_ok=True)

In [53]:
from sqlalchemy import text

q1 = pd.read_sql(text("""
    SELECT
        ROUND(AVG(ingredient)::numeric, 4) AS ingredient_rate,
        ROUND(AVG(price)::numeric, 4)      AS price_rate,
        ROUND(AVG(result)::numeric, 4)     AS result_rate,
        ROUND(AVG(authority)::numeric, 4)  AS authority_rate,
        ROUND(AVG(brand)::numeric, 4)      AS brand_rate,
        COUNT(*)                           AS total_reviews
    FROM antispot_reviews_signals
"""), engine)

q2 = pd.read_sql(text("""
    SELECT
        skin_type,
        ROUND(AVG(ingredient)::numeric, 4) AS ingredient_rate,
        ROUND(AVG(price)::numeric, 4)      AS price_rate,
        ROUND(AVG(result)::numeric, 4)     AS result_rate,
        ROUND(AVG(authority)::numeric, 4)  AS authority_rate,
        ROUND(AVG(brand)::numeric, 4)      AS brand_rate,
        COUNT(*)                           AS sample_size
    FROM antispot_reviews_signals
    WHERE skin_type IS NOT NULL
    GROUP BY skin_type
    ORDER BY sample_size DESC
"""), engine)

q3 = pd.read_sql(text("""
    WITH ingredient_mentions AS (
        SELECT
            CASE
                WHEN review_text ILIKE '%niacinamide%' THEN 'niacinamide'
                WHEN review_text ILIKE '%vitamin c%'   THEN 'vitamin_c'
                WHEN review_text ILIKE '%retinol%'     THEN 'retinol'
                WHEN review_text ILIKE '%glycolic%'    THEN 'glycolic_acid'
                WHEN review_text ILIKE '%tranexamic%'  THEN 'tranexamic_acid'
                ELSE NULL
            END AS mentioned_ingredient,
            rating::numeric,
            is_recommended::numeric
        FROM antispot_reviews_signals
    )
    SELECT
        mentioned_ingredient,
        ROUND(AVG(rating), 2)         AS avg_rating,
        ROUND(AVG(is_recommended), 2) AS recommend_rate,
        COUNT(*)                      AS mention_count,
        RANK() OVER (ORDER BY AVG(rating) DESC) AS satisfaction_rank
    FROM ingredient_mentions
    WHERE mentioned_ingredient IS NOT NULL
    GROUP BY mentioned_ingredient
    ORDER BY satisfaction_rank
"""), engine)

q4 = pd.read_sql(text("""
    SELECT
        CASE
            WHEN ingredient = 1 AND brand = 0 AND authority = 0 THEN 'ingredient_driven'
            WHEN brand = 1 AND ingredient = 0 AND authority = 0 THEN 'brand_driven'
            WHEN authority = 1                                   THEN 'authority_influenced'
            WHEN price = 1 AND ingredient = 0                   THEN 'price_motivated'
            WHEN result = 1 AND ingredient = 0                  THEN 'result_focused'
            ELSE 'mixed_or_none'
        END AS primary_driver,
        ROUND(AVG(rating::numeric), 2)         AS avg_rating,
        ROUND(AVG(is_recommended::numeric), 2) AS recommend_rate,
        COUNT(*)                               AS review_count
    FROM antispot_reviews_signals
    GROUP BY primary_driver
    ORDER BY recommend_rate DESC
"""), engine)

output = Path("C:/Users/super/Projects/skincare-sentiment-analysis/data/output")
q1.to_csv(output / "signal_overall.csv", index=False)
q2.to_csv(output / "signal_by_skintype.csv", index=False)
q3.to_csv(output / "ingredient_satisfaction.csv", index=False)
q4.to_csv(output / "driver_satisfaction.csv", index=False)

print("Done")

Done